version: '3'
services:
  mongo:
    image: 'mongo:4.0.18'
    restart: always
    #    ports:
    #      - '27017:27017'
  redis:
    image: 'redis:6.0.4'
    restart: always
    #    ports:
    #      - '6379:6379'
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: 'production'
      REDIS_HOST: 'redis'
      MONGO_HOST: 'mongo'
    depends_on:
      - mongo
      - redis
